apiVersion: v1
kind: Pod
metadata:
  name: hostpath-vol-pod1
spec:
  containers:
   - name: test-container
     image: busybox
     command: ['sh', '-c', 'sleep 3600']
     volumeMounts:
      - name: hostpath-volume
        mountPath: /test
  volumes:
   - name: hostpath-volume
     hostPath:
       path: /tmp/data      # directory location on host
       type: Directory  # this field is optional
