apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - us-east
            - us-west
              #      preferredDuringSchedulingIgnoredDuringExecution:
              #      - weight: 1
              #        preference:
              #          matchExpressions:
              #          - key: env
              #            operator: In
              #            values:
              #            - prod
  containers:
  - name: with-node-affinity
    image: lerndevops/tomcat:8.5.47
    ports:
      - containerPort: 8080
