apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: sampleapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: apache
        image: httpd
        ports:
         - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 80  # inside container
#    nodePort: 30001 #expose , if dont give takes default
    protocol: TCP
  selector:
    tier: frontend
